// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// muScoreOB
Rcpp::NumericVector muScoreOB(const Rcpp::DataFrame& df);
RcppExport SEXP _RepSeq_muScoreOB(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(muScoreOB(df));
    return rcpp_result_gen;
END_RCPP
}
// muScoreM
Rcpp::NumericMatrix muScoreM(const Rcpp::DataFrame& df);
RcppExport SEXP _RepSeq_muScoreM(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(muScoreM(df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RepSeq_muScoreOB", (DL_FUNC) &_RepSeq_muScoreOB, 1},
    {"_RepSeq_muScoreM", (DL_FUNC) &_RepSeq_muScoreM, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RepSeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
