# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute muScore
#'
#' This function returns multivariate score for each row of the input mumerical data set using the O'Brien (1984)'s method.
#' @param df a data frame of counts with samples in columns and clonotypes in rows
#' @return a vector of multivariate scores computed for each row 
#' @export
muScoreOB <- function(df) {
    .Call('_RepSeq_muScoreOB', PACKAGE = 'RepSeq', df)
}

#' compute pre-muScore matrix
#' This function returns a matrix of scores comparing pairwise rows for each sample of the input data set. 
#'
#' @param df a data frame of counts with samples in columns and clonotypes in rows. 
#' @return a matrix  
#' @export
muScoreM <- function(df) {
    .Call('_RepSeq_muScoreM', PACKAGE = 'RepSeq', df)
}

